#ifndef picox_config_h_
#define picox_config_h_


#define X_CONFIG_USE_FLOATING_POINT_PRINTF  (1)
#define X_CONF_HAS_C99_MATH                 (1)
#define X_CONF_XFS_TYPE                     (X_XFS_TYPE_UNION_FS)
// #define X_CONF_XFS_TYPE                     (X_XFS_TYPE_SINGLE_FS)

#define X_CONF_TICKS_NOW_IMPL_TYPE      X_TICKS_NOW_IMPL_TYPE_GETTIMEOFDAY
#define X_CONF_GETTIMEOFDAY_IMPL_TYPE   X_GETTIMEOFDAY_IMPL_TYPE_POSIX
#define X_CONF_MSLEEP_IMPL_TYPE         X_MSLEEP_IMPL_TYPE_POSIX_NANOSLEEP
#define X_CONF_USLEEP_IMPL_TYPE         X_MSLEEP_IMPL_TYPE_POSIX_NANOSLEEP
#define X_CONF_MDELAY_IMPL_TYPE         X_MDELAY_IMPL_TYPE_POSIX_NANOSLEEP
#define X_CONF_UDELAY_IMPL_TYPE         X_MDELAY_IMPL_TYPE_POSIX_NANOSLEEP


#endif /* picox_config_h_ */
